site_name: AzureClusterlessHPC
site_description: Simplified distributed computing on Azure
site_url: https://microsoft.github.io/AzureClusterlessHPC.jl/
repo_url: https://github.com/microsoft/AzureClusterlessHPC.jl

nav:
    - Home: index.md
    - Installation: installation.md
    - Quickstart: quickstart.md
    - Credentials: credentials.md
    - Manage pools: pool.md
    - Remote function calls: functioncalls.md
    - Broadcasting: broadcasting.md
    - Collect output: output.md
    - Clean up: cleanup.md
    - FAQ: faq.md
    - About: about.md

theme: readthedocs

copyright: Copyright (c) Microsoft Corporation. All rights reserved.

plugins:
    - search